### ISSUE TITLE
Get out of Jail - UI

### ISSUE THREAD

**Issue by majasmolej** [gammaStrahlung/monopoly_app#22]
When it's the player's turn, notify them they are in Jail and what the conditions are to get out.
Your turn is suspended until you:

- roll doubles
- use get out of Jail Free Card
- pay 50 fine

You can stay in Jail max 3 turns.

**Comment by pomegr4nate** [comment]
This has been added here:
https://github.com/gammaStrahlung/monopoly_app/pull/52
